### ISSUE TITLE
Compilation fails with latest version of Monero codebase repository

### ISSUE THREAD

**Issue by serhack** [vtnerd/monero-lws#13]
Steps to reproduce:
- Clone the monero-code/monero repository
- Build Monero binaries
- Clone Monero lws repository
- Try to build Light wallet server

Version:
GCC 7 Debian 10

Error:
`no member named increase_size in epee:byte_stream`

For now, you should `git checkout release-v017` on Monero repository since the light wallet actually compiles with the 0.17 release of Monero.

**Comment by vtnerd** [comment]
I'm not sure this is a workaround, as this is intentional for now. The readme might need updating though.

**Comment by vtnerd** [comment]
This should now be [fixed](https://github.com/vtnerd/monero-lws/commit/dbbdee6fd4ba81125a9454d7dbecbff5d4196368)

**Comment by vtnerd** [comment]
Also, there are now three major branches `master`, `develop`, and `release_v0.1_0.17`. The first two are to be compiled against `monero-project/monero/master` and the last one against `monero-project/monero/release-v0.17`

**Comment by trasherdk** [comment]
Argh... `release_v0.1_0.17` => `release-v0.1_0.17`

```sh
Fetching origin ...
checkout release_v0.1_0.17 ...
error: pathspec 'release_v0.1_0.17' did not match any file(s) known to git.
```
It took a few head scratches and wtf's before arriving at
```sh
$ git branch -a
* develop
  remotes/origin/HEAD -> origin/develop
  remotes/origin/develop
  remotes/origin/master
  remotes/origin/release-v0.1_0.17
```
